<?php declare(strict_types=1);
/**
 *  This file is part of the Propel package.
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 *
 * @license MIT License
 */

namespace Propel\Generator\Builder\Om\Component\Object;


use Propel\Generator\Builder\Om\Component\BuildComponent;

class ClassDescription extends BuildComponent
{
    public function process(): void
    {
        $description[] = "Base class that represents a row from the '{$this->getTable()->getName()}' table.";
        $description[] = "";
        $description[] = $this->getTable()->getDescription();
        $description[] = "";

        if ($this->getBuilder()->getBuildProperty('generator.objectModel.addTimeStamp')) {
            $now = strftime('%c');
            $description[] = "This class was autogenerated by Propel {$this->getBuilder()->getBuildProperty('general.version')} on:";
            $description[] = "";
            $description[] = $now;
        }

        $this->getDefinition()->setMultilineDescription($description);
    }
}
