<?php declare(strict_types=1);
/**
 *  This file is part of the Propel package.
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 *
 * @license MIT License
 */

namespace Propel\Generator\Builder\Om;

/**
 * Generates the empty PHP stub class for object query
 *
 * This class produces the empty stub class that can be customized with application
 * business logic, custom behavior, etc.
 *
 * @author Marc J. Schmidt <marc@marcjschmidt.de>
 */
class StubObjectBuilder extends AbstractBuilder
{
    public function buildClass(): void
    {
        $parentClass = $this->getObjectBuilder()->getFullClassName();
        $shortClass = $this->getDefinition()->declareUse($parentClass);
        $this->getDefinition()
            ->setParentClassName($shortClass)
            ->setAbstract($this->getTable()->isAbstract())
        ;

        if (true === $this->getBuildProperty('generator.objectModel.addClassLevelComment')) {
            $description[] = "Skeleton subclass for representing a row from the '{$this->getTable()->getName()->toString()}' table.";
            $description[] = '';
            $description[] = "{$this->getTable()->getDescription()}";
            $description[] = '';
            if ($this->getBuildProperty('generator.objectModel.addTimeStamp')) {
                $now = strftime('%c');
                $description[] = "This class was autogenerated by Propel {$this->getBuildProperty('general.version')} on: $now";
            }
            $description[] = "You should add additional methods to this class to meet the";
            $description[] = "application requirements.  This class will only be generated as";
            $description[] = "long as it does not already exist in the output directory.";

            $this->getDefinition()->setMultilineDescription($description);
        }
    }
}
